package vn.uit.lms.core.domain.course.content;

import jakarta.persistence.*;
import lombok.*;
import vn.uit.lms.shared.constant.ResourceType;
import vn.uit.lms.shared.entity.BaseEntity;

/**
 * LessonResource Entity
 *
 * Relationship Type: COMPOSITION
 * - Parent: Lesson (owns LessonResource)
 * - When Lesson is deleted → LessonResource is deleted
 * - LessonResource cannot exist without Lesson
 *
 * Referenced:
 * - FileStorage: ASSOCIATION (FileStorage exists independently, NO CASCADE)
 */
@Entity
@Table(name = "lesson_resources", indexes = {
        @Index(name = "idx_resource_lesson", columnList = "lesson_id"),
        @Index(name = "idx_resource_type", columnList = "resource_type")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LessonResource extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // COMPOSITION: LessonResource belongs to Lesson
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lesson_id", nullable = false)
    private Lesson lesson;

    @Enumerated(EnumType.STRING)
    @Column(name = "resource_type", length = 20, nullable = false)
    private ResourceType resourceType;

    @Column(name = "title", nullable = false, length = 512)
    private String title;

    @Column(name = "description", length = 2048)
    private String description;

    // ASSOCIATION: FileStorage exists independently
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "file_storage_id")
    private FileStorage fileStorage;

    @Column(name = "external_url", columnDefinition = "TEXT")
    private String externalUrl;

    @Column(name = "order_index", nullable = false)
    private Integer orderIndex = 0;


    @Column(name = "is_required", nullable = false)
    private Boolean isRequired = false;

    @Column(name = "file_size_bytes")
    private Long fileSizeBytes;


    /**
     * Check if this is a FILE resource (uploaded file)
     */
    public boolean isFileResource() {
        return resourceType == ResourceType.FILE;
    }

    /**
     * Check if this is a LINK resource (external URL)
     */
    public boolean isLinkResource() {
        return resourceType == ResourceType.LINK;
    }

    /**
     * Check if this is an EMBED resource (iframe embeddable)
     */
    public boolean isEmbedResource() {
        return resourceType == ResourceType.EMBED;
    }

    /**
     * Check if resource is downloadable
     * Only FILE resources can be downloaded
     */
    public boolean isDownloadable() {
        return isFileResource() && fileStorage != null;
    }

    /**
     * Get display URL for frontend
     *
     * FILE: null (URL generated by service layer from fileStorage)
     * LINK/EMBED: externalUrl
     */
    public String getDisplayUrl() {
        if (isFileResource()) {
            return null; // URL generated runtime by FileStorageService
        }
        return externalUrl;
    }

    /**
     * Get file name (for FILE type)
     */
    public String getFileName() {
        if (isFileResource() && fileStorage != null) {
            return fileStorage.getOriginalName();
        }
        return null;
    }

    /**
     * Get formatted file size (for FILE type)
     */
    public String getFormattedFileSize() {
        if (fileSizeBytes == null || fileSizeBytes == 0) {
            return "0 KB";
        }

        if (fileSizeBytes < 1024) {
            return fileSizeBytes + " B";
        } else if (fileSizeBytes < 1024 * 1024) {
            return String.format("%.1f KB", fileSizeBytes / 1024.0);
        } else if (fileSizeBytes < 1024 * 1024 * 1024) {
            return String.format("%.1f MB", fileSizeBytes / (1024.0 * 1024.0));
        } else {
            return String.format("%.1f GB", fileSizeBytes / (1024.0 * 1024.0 * 1024.0));
        }
    }

    /**
     * Sync file size from FileStorage
     * Called after setting fileStorage
     */
    public void syncFileSizeFromStorage() {
        if (fileStorage != null) {
            this.fileSizeBytes = fileStorage.getSizeBytes();
        }
    }

    /**
     * Validate resource constraints
     *
     * Business rules:
     * 1. FILE type must have fileStorage (no externalUrl)
     * 2. LINK/EMBED must have externalUrl (no fileStorage)
     *
     * NOTE: Call this method in service before persisting to avoid @PrePersist conflict with BaseEntity
     */
    public void validateResource() {
        if (resourceType == null) {
            throw new IllegalStateException("Resource type is required");
        }

        switch (resourceType) {
            case FILE:
                if (fileStorage == null) {
                    throw new IllegalStateException("FILE resource must have fileStorage");
                }
                if (externalUrl != null) {
                    throw new IllegalStateException("FILE resource should not have externalUrl");
                }
                // Sync file size
                syncFileSizeFromStorage();
                break;

            case LINK:
            case EMBED:
                if (externalUrl == null || externalUrl.isBlank()) {
                    throw new IllegalStateException(resourceType + " resource must have externalUrl");
                }
                if (fileStorage != null) {
                    throw new IllegalStateException(resourceType + " resource should not have fileStorage");
                }
                break;
        }

        // Ensure orderIndex is not null
        if (orderIndex == null) {
            orderIndex = 0;
        }

        // Ensure isRequired is not null
        if (isRequired == null) {
            isRequired = false;
        }
    }

    /**
     * Update resource basic info
     */
    public void updateBasicInfo(String title, String description, Boolean isRequired) {
        if (title != null && !title.isBlank()) {
            this.title = title;
        }
        this.description = description;
        if (isRequired != null) {
            this.isRequired = isRequired;
        }
    }

    /**
     * Update external URL (for LINK/EMBED types)
     */
    public void updateExternalUrl(String newUrl) {
        if (!isLinkResource() && !isEmbedResource()) {
            throw new IllegalStateException("Can only update external URL for LINK/EMBED resources");
        }
        if (newUrl == null || newUrl.isBlank()) {
            throw new IllegalArgumentException("External URL cannot be empty for LINK/EMBED resources");
        }
        this.externalUrl = newUrl;
    }

    /**
     * Update order index
     */
    public void updateOrderIndex(Integer newOrderIndex) {
        if (newOrderIndex != null && newOrderIndex >= 0) {
            this.orderIndex = newOrderIndex;
        }
    }

    /**
     * Replace file storage (for FILE type)
     */
    public void replaceFileStorage(FileStorage newFileStorage) {
        if (!isFileResource()) {
            throw new IllegalStateException("Can only replace file storage for FILE resources");
        }
        if (newFileStorage == null) {
            throw new IllegalArgumentException("New file storage cannot be null");
        }
        this.fileStorage = newFileStorage;
        syncFileSizeFromStorage();
    }
}
